### ISSUE TITLE
What ML model did you use?

### ISSUE THREAD

**Issue by topcoder20022** [Supernova1024/3Curvefilter#1]
I'd like to use this repository for my project.
I want to know what kind of ML model did you use?

**Comment by dragonstar41** [comment]
I think CNN model is used in this repository

**Comment by Supernova1024** [comment]
Yes, certainly
Hi, topcoder
Are you satisfied the answer?

**Comment by topcoder20022** [comment]
Sure, thanks, Supernova and Dragonstar

**Comment by Supernova1024** [comment]
Ok, I will close this issue
